In [81]:
import numpy as np
my_data = np.genfromtxt('Assignment4Data.csv', delimiter=',', dtype='int32')  # all data at csv
my_data

array([[  -1,   -1,   -1, ...,   -1,   -1,   -1],
       [2013,   -1, 1224, ...,   -1,   -1,   -1],
       [2013,   -1, 1679, ...,   -1,   -1,   -1],
       ...,
       [2020,   -1, 9858, ...,   -1,   -1,   -1],
       [2020,   -1, 9860, ...,   -1,   -1,   -1],
       [2020,   -1, 9865, ...,   -1,   -1,   -1]])

In [82]:
my_data2 = my_data[1:,[0,2,3,4,5]].copy()  # remove first row (headers), take columns 0,2,3,4,5
my_data2

array([[2013, 1224,  591,  572,  558],
       [2013, 1679,  472,  346,    0],
       [2013, 9626,   45,   57,   52],
       [2013, 9806,  160,  176,  189],
       [2013, 9813,  426,  483,  567],
       [2013, 9815,  620,  584,  585],
       [2013, 9816,  658,  631,  632],
       [2013, 9823,  289,  280,  311],
       [2013, 9825,  496,  465,  528],
       [2013, 9826,  523,  467,  517],
       [2013, 9829,  487,  413,  457],
       [2013, 9830,   29,   29,   45],
       [2013, 9836,  399,  361,  380],
       [2013, 9847,  210,  225,  359],
       [2013, 9850,  657,  566,  501],
       [2013, 9856,  163,  146,  228],
       [2013, 9857,  587,  611,  648],
       [2013, 9858,  514,  577,  522],
       [2013, 9860,  435,  364,  509],
       [2013, 9865,  504,  530,  512],
       [2014, 1224,  599,  592,  598],
       [2014, 1679,  444,  452,  341],
       [2014, 9626,   40,   49,   55],
       [2014, 9806,  151,  137,  173],
       [2014, 9813,  430,  404,  572],
       [2014, 9815,  662,

In [83]:
my_data_yearly = my_data2.reshape(8,20,5)
my_data_yearly

array([[[2013, 1224,  591,  572,  558],
        [2013, 1679,  472,  346,    0],
        [2013, 9626,   45,   57,   52],
        [2013, 9806,  160,  176,  189],
        [2013, 9813,  426,  483,  567],
        [2013, 9815,  620,  584,  585],
        [2013, 9816,  658,  631,  632],
        [2013, 9823,  289,  280,  311],
        [2013, 9825,  496,  465,  528],
        [2013, 9826,  523,  467,  517],
        [2013, 9829,  487,  413,  457],
        [2013, 9830,   29,   29,   45],
        [2013, 9836,  399,  361,  380],
        [2013, 9847,  210,  225,  359],
        [2013, 9850,  657,  566,  501],
        [2013, 9856,  163,  146,  228],
        [2013, 9857,  587,  611,  648],
        [2013, 9858,  514,  577,  522],
        [2013, 9860,  435,  364,  509],
        [2013, 9865,  504,  530,  512]],

       [[2014, 1224,  599,  592,  598],
        [2014, 1679,  444,  452,  341],
        [2014, 9626,   40,   49,   55],
        [2014, 9806,  151,  137,  173],
        [2014, 9813,  430,  404,  572]

In [84]:
filter = np.asarray([1679])
school_view = my_data2[np.in1d(my_data2[:, 1], filter)]
school_view

array([[2013, 1679,  472,  346,    0],
       [2014, 1679,  444,  452,  341],
       [2015, 1679,  419,  411,  463],
       [2016, 1679,  345,  396,  436],
       [2017, 1679,  433,  374,  450],
       [2018, 1679,  398,  423,  391],
       [2019, 1679,  355,  430,  455],
       [2020, 1679,  360,  352,  437]])

In [85]:
school_view[:,2:]

array([[472, 346,   0],
       [444, 452, 341],
       [419, 411, 463],
       [345, 396, 436],
       [433, 374, 450],
       [398, 423, 391],
       [355, 430, 455],
       [360, 352, 437]])

In [86]:
print(school_view[:,2:].max())
print(school_view[:,2:].min())

472
0


In [87]:
school_view[:,2:].sum(axis=1)  # collapse on rows

array([ 818, 1237, 1293, 1177, 1257, 1212, 1240, 1149])

In [93]:
my_data_yearly[0,:,2:].mean()  # 2013 total mean

404.1333333333333

In [97]:
my_data_yearly[7,:,2:].mean()  # 2020 total mean

404.8666666666667

In [106]:
my_data_yearly[7,:,4].sum()  # 2020 total grad class

8281

In [109]:
my_data_yearly[:,:,2:].max()

798

In [110]:
my_data_yearly[:,:,2:].min()

0